server.port=8081

# Configurações do Banco de Dados PostgreSQL (Neon via .env)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Desabilita o console do H2 (já que agora usamos PostgreSQL)
spring.h2.console.enabled=false

# Configurações da API Twelve Data
twelve-data.api-key=${DB_TWELVEDATAKEY}
twelve-data.base-url=https://api.twelvedata.com

# Tickers totais
app.tickers.fixos=AAPL,MSFT,NVDA,AMZN,GOOGL